name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: 
  push:
    paths:
      - '**.py'
jobs:
  run-pytest:
    runs-on: ubuntu-latest
    steps:
    - run:  echo "Setting up checking out repo"
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.ref }}
    - run:  echo "Setting up Python"
    - uses: actions/setup-python@v4
      with:
        python-version: '3.11' 
        cache: 'pip'
    - run:  pip install -r requirements.txt
    - run: pytest -vrP