name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [ push ]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
    - run: echo "Running hello.py"
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.11' 
    - run: python hello.py